# Dev overrides

version: "2.0"

services:
  mongodb:
    ports:
      - "27017:27017"

  api:
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/api/
    entrypoint:
      - "gunicorn"
      - "-b"
      - "0.0.0.0:8000"
      - "urlinfo:app"
